apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::905418383993:role/eksctl-expense-1-nodegroup-ng-1-NodeInstanceRole-TjjGTs6PUUCI
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-admin
      userarn: arn:aws:iam::905418383993:user/gani
      username: gani
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-25T08:59:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1336"
  uid: e3835547-4d16-4e61-a5b4-ccfab99eba4d
